### ISSUE TITLE
proper working example of consul-template usage?

### ISSUE THREAD

**Issue by sigurdblueface** [bank-vaults/vault-secrets-webhook#303]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-secrets-webhook/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Problem Description

I'm trying to mount my secrets as files using consul-templates mechanism. But snippets from official doc doesn't seem to work. It's either syntax errors or inability to access secrets from vault. 
I'm getting an error:
```
/vault/ct-config/config.hcl: mapstructure decode failed: 1 error(s) decoding:`
* '' has invalid keys: auto_auth

```
my cm is like:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-example-inject-template
data:
  config.hcl: |
    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes"
            config = {
                role = "<role>"
            }
        }
        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
            }
        }
    }
    ...
```

Could please anyone provide me with an actual working example?

### Proposed Solution

Please provide an example.

### Alternatives Considered

tried many snippets from web.

**Comment by sigurdblueface** [comment]
For the future generations:
```yaml
apiVersion: v1
kind: ConfigMap
...
data:
  config.hcl: |
    log_level = "debug"
    vault {
      vault_agent_token_file = "/vault/.vault-token"
      retry {
        backoff = "1s"
      }
    }
    template {
      contents = <<EOH
        {{`{{- with secret "`}}{{ .Values.vault.secretPath }}{{`" -}}`}}
        ... <reference your secrets here like .Data.data.<secret name>>
        {{`{{- end -}}`}}
      EOH
      destination = "/vault/secrets/secret-file"
    }

```

And following set of annotations:
```yaml
# related to vault in general
vault.security.banzaicloud.io/vault-addr: {{ .address }}
vault.security.banzaicloud.io/vault-path: {{ .path }}
vault.security.banzaicloud.io/vault-skip-verify: "true"
vault.security.banzaicloud.io/vault-role: {{ .role }}
vault.security.banzaicloud.io/vault-serviceaccount: {{ .serviceAccount }}
# consul-template related:
vault.security.banzaicloud.io/vault-ct-configmap: <name of the configmap with config.hcl>
vault.security.banzaicloud.io/vault-ct-image: "hashicorp/consul-template:0.36"
vault.security.banzaicloud.io/vault-ct-secrets-mount-path: <path where to mount the volume with secrets>
# to disable daemon mode, to make this thing acting like a typical initContainer
vault.security.banzaicloud.io/vault-ct-once: "true"
```
