### ISSUE TITLE
injected secrets can't be printed in container

### ISSUE THREAD

**Issue by azizkarimovv** [bank-vaults/vault-secrets-webhook#384]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-secrets-webhook/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Problem Description

When executing into pod, the `env` command does not print the variables injected into a container. 

### Proposed Solution

There can be 2 modes of injection. The first one is hidden and the secrets injected by vault-agent can be accessed only by main process. The second mode enables accessibility, so the secret injected can be accessed by any session.  Is it possible to add an annotation to switch between modes.

**Comment by sagikazarmark** [comment]
@azizkarimovv technically, secrets are not injected into the pod as env vars, rather the entrypoint is prepended with a custom binary that replaces the secret references and executes the original command.

Try running `/vault/vault-env env`. You should see the secret values in env vars.

**Comment by ramizpolic** [comment]
Closing as this is expected behaviour, check @sagikazarmark onto why

**Comment by SergeiCherevko** [comment]
Hello guys! Sorry me but i have a stupid question how to use variable not by ```/vault/vault-env env```?

For example i want just print in container output
I have this simple pod
```
apiVersion: v1
kind: Pod
metadata:
  name: vault-var
  namespace: argocd
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://${RANDOM_PET}-vault.totalbattle-playground.com"
    vault.security.banzaicloud.io/vault-role: "k8s-read-role"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
spec:
  serviceAccountName: vault-webhook
  containers:
    - name: vault-var
      image: busybox
      command: ["sh", "-c", "echo SECRET: $MYSECRET && echo going to sleep... && sleep 10000"]
      env:
        - name: MYSECRET
          value: vault:secret/data/k8s/test#username
```

and my output logs is
```
kubectl logs -n argocd vault-var
Defaulted container "vault-var" out of: vault-var, copy-vault-env (init)
time="2024-07-17T09:15:36Z" level=info msg="received new Vault token" addr= app=vault-env path=kubernetes role=k8s-read-role
time="2024-07-17T09:15:36Z" level=info msg="initial Vault token arrived" app=vault-env
time="2024-07-17T09:15:36Z" level=info msg="spawning process: [sh -c echo SECRET:  && echo going to sleep... && sleep 10000]" app=vault-env
SECRET:
going to sleep...
```

Please help me to understand what the problem
