### ISSUE TITLE
Unable to mutate Cluster Scoped CRD

### ISSUE THREAD

**Issue by tvarade** [bank-vaults/vault-secrets-webhook#385]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-secrets-webhook/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://bank-vaults.dev/docs/support/) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Vault Secrets Webhook Version

1.19.0

### Installation Type

Official Helm chart

### Kubernetes Version

1.25

### Kubernetes Distribution/Provisioner

EKS

### Expected Behavior

When I provide all required annotation secret should get injected to my CRD

### Actual Behavior

Secrets not getting injected into CRD.
I still see vault path

### Steps To Reproduce

Deploy any cluster scope CRD and try to mutate it with annotation.

### Logs

```shell
time="2024-03-29T13:53:47Z" level=error msg="Admission review request failed" app=vault-secrets-webhook dry-run=false error="failed to create vault client: Failed to retrieve specified service account on namespace : an empty namespace may not be set when a resource name is provided" kind=rds.aws.crossplane.io/v1alpha1/DBCluster name=tvarade-database ns= op=update path=/objects request-id=012462fb-44fe-413e-b528-45003e2fc1d7 webhook-id=vault-secrets-object webhook-kind=mutating wh-version=v1beta1
time="2024-03-29T13:53:48Z" level=error msg="failed to request new Vault token" app=vault-secrets-webhook err="Error making API request.\n\nURL: PUT https://vault.com/v1/auth/k8s/login\nCode: 403. Errors:\n\n* permission denied"
```
```

**Comment by akijakya** [comment]
Hi @tvarade, if you still have this issue, could you share the annotations you set? Thanks!

**Comment by tvarade** [comment]
Hi @akijakya 
```
annotations:
    vault.security.banzaicloud.io/vault-addr: "vault addr"
    vault.security.banzaicloud.io/vault-path: "k8s"
    vault.security.banzaicloud.io/vault-role: "k8s-role"
    vault.security.banzaicloud.io/vault-skip-verify: "false"
    vault.security.banzaicloud.io/vault-tls-secret: ca
    vault.security.banzaicloud.io/vault-serviceaccount: "sa"
```
here is the list of annotation i am using
