### ISSUE TITLE
Is it mandatory to have ClusterRole or Will it be sufficient with a Role instead

### ISSUE THREAD

**Issue by vishnu-anil** [bank-vaults/vault-secrets-webhook#43]
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "vault-secrets-webhook.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
 ```

Currently the chart creates clusterrole and looks overpermissive giving access to secrets as Clusterrole is not namespaced. Is there a way to limit this. Can we use Role instead?
