### ISSUE TITLE
Generate secret token for vault-webhook-service-account

### ISSUE THREAD

**Issue by SergeiCherevko** [bank-vaults/vault-secrets-webhook#596]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-secrets-webhook/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Problem Description

After deploying the vault-webhook via Helm, we need to manually add a secret with a token to the Vault service account to pass this JWT to Vault.

Why don't you create a template to generate the secret?
Here, you create the service account:
https://github.com/bank-vaults/vault-secrets-webhook/blob/main/deploy/charts/vault-secrets-webhook/templates/webhook-rbac.yaml
So, why not include the generation of the JWT token secret here as well?
This way, for every new cluster, we only need to create an ArgoCD application to add a single manifest that generates the secret token for the existing Vault webhook service account.

### Proposed Solution

add to this rbac manifest rbac template
```
apiVersion: v1
kind: Secret
metadata:
  name: vault-webhook-jwt-token
  namespace: vault
  annotations:
    kubernetes.io/service-account.name: {{ template "vault-secrets-webhook.serviceAccountName" . }}
type: kubernetes.io/service-account-token
```
